name: Docker Build and Push

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Read version
      id: read_version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          xhtnext/azure-openai-proxy:latest
          xhtnext/azure-openai-proxy:${{ github.sha }}
          xhtnext/azure-openai-proxy:${{ env.VERSION }}
